spring.application.name=escape-planner

server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/escape_planner}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
#Impide que hibernate modifique tablas automaticamente
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
#Se desactiva Open Session in View para evitar consultas implícitas en la capa de vista y mantener una separación clara entre capas buena práctica
spring.jpa.properties.hibernate.format_sql=true
#Hace que las consultas se vean más ordenadas y legibles
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#Evita inconsistencias de fechas y horas entre sistema, base y aplicación
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Se especifica el dialecto de PostgreSQL para que Hibernate genere consultas SQL compatibles con este motor de base de datos.

spring.sql.init.mode=never
#Se desactiva la ejecución automática de scripts SQL porque la base de datos se gestiona manualmente mediante scripts definidos en el proyecto.

spring.thymeleaf.cache=false
#Se desactiva el caché de Thymeleaf para reflejar cambios en vistas inmediatamente durante el desarrollo sin reiniciar la aplicación.

logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=INFO
